services:
    fullstack:
        build:
            context: .
            dockerfile: Dockerfile
        image: capstone
        container_name: capstone
        volumes:
            - ./frontend:/app/frontend
            - ./backend:/app/backend
            - ./.vscode:/app/.vscode
            - ./requirements.txt:/app/requirements.txt
            - ./.devcontainer:/app/.devcontainer
            - ./gitignore:/app/.gitignore
            - ./startup.sh:/app/startup.sh
        ports:
            - '5173:5173'
            - '3000:3000'
            - '8000:8000'
