FROM node:24.2.0-alpine3.22
COPY ./frontend /app/frontend
COPY ./.vscode /app/.vscode
COPY ./.git /app/.git
RUN rm -rf /app/frontend/node_modules

WORKDIR /app/frontend
RUN npm ci

CMD ["npm", "run", "dev"]
