services:
    fullstack:
        build:
            context: .
            dockerfile: Dockerfile
        image: capstone:fullstack
        container_name: capstone-fullstack
        volumes:
            - ./frontend:/app/frontend
            - ./backend:/app/backend
            - ./.vscode:/app/.vscode
            - ./requirements.txt:/app/requirements.txt
            - ./backend/db.sqlite3:/app/backend/db.sqlite3
            - ~/.gitconfig:/home/appuser/.gitconfig:ro
        ports:
            - '5173:5173'
            - '3000:3000'
            - '8000:8000'
