INSERT INTO ledgers_coacategory (category_name,created_at,updated_at) VALUES ('Sales',DATETIME(),DATETIME());
INSERT INTO ledgers_coacategory (category_name,created_at,updated_at) VALUES ('Purchases',DATETIME(),DATETIME());
INSERT INTO ledgers_coacategory (category_name,created_at,updated_at) VALUES ('Direct Expenses',DATETIME(),DATETIME());
INSERT INTO ledgers_coacategory (category_name,created_at,updated_at) VALUES ('Overheads',DATETIME(),DATETIME());
INSERT INTO ledgers_coacategory (category_name,created_at,updated_at) VALUES ('Taxation',DATETIME(),DATETIME());
INSERT INTO ledgers_coacategory (category_name,created_at,updated_at) VALUES ('Fixed Assets',DATETIME(),DATETIME());
INSERT INTO ledgers_coacategory (category_name,created_at,updated_at) VALUES ('Current Assets',DATETIME(),DATETIME());
INSERT INTO ledgers_coacategory (category_name,created_at,updated_at) VALUES ('Current Liabilities',DATETIME(),DATETIME());
INSERT INTO ledgers_coacategory (category_name,created_at,updated_at) VALUES ('Long Term Liabilities',DATETIME(),DATETIME());
INSERT INTO ledgers_coacategory (category_name,created_at,updated_at) VALUES ('Capital & Reserves',DATETIME(),DATETIME());
