INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (0010,'Freehold Property',DATETIME(),DATETIME(),30,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (0011,'Leasehold Property',DATETIME(),DATETIME(),30,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (0020,'Plant and Machinery',DATETIME(),DATETIME(),31,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (0021,'Plant/Machinery Depreciation',DATETIME(),DATETIME(),31,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (0030,'Office Equipment',DATETIME(),DATETIME(),32,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (0031,'Office Equipment Depreciation',DATETIME(),DATETIME(),32,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (0040,'Furniture and Fixtures',DATETIME(),DATETIME(),33,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (0041,'Furniture/Fixture Depreciation',DATETIME(),DATETIME(),33,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (0050,'Motor Vehicles',DATETIME(),DATETIME(),34,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (0051,'Motor Vehicles Depreciation',DATETIME(),DATETIME(),34,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1001,'Stock',DATETIME(),DATETIME(),35,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1002,'Work in Progress',DATETIME(),DATETIME(),35,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1003,'Finished Goods',DATETIME(),DATETIME(),35,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1004,'Raw Materials',DATETIME(),DATETIME(),35,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1100,'Debtors Control Account',DATETIME(),DATETIME(),36,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1101,'Sundry Debtors',DATETIME(),DATETIME(),36,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1102,'Other Debtors',DATETIME(),DATETIME(),36,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1103,'Prepayments',DATETIME(),DATETIME(),36,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1104,'Inter-company Debtors',DATETIME(),DATETIME(),36,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1105,'Provision for credit notes',DATETIME(),DATETIME(),36,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1106,'Provision for doubtful debts',DATETIME(),DATETIME(),36,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1107,'Deposits Paid',DATETIME(),DATETIME(),36,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1110,'Directors Loan Account',DATETIME(),DATETIME(),36,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1199,'VAT on doubtful debts',DATETIME(),DATETIME(),36,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1200,'Business Current Account',DATETIME(),DATETIME(),39,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1205,'Business Paypal Account',DATETIME(),DATETIME(),39,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1209,'Suspense Bank Account',DATETIME(),DATETIME(),39,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1210,'Tax Saver Account',DATETIME(),DATETIME(),37,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1220,'Building Society Account',DATETIME(),DATETIME(),37,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1230,'Petty Cash',DATETIME(),DATETIME(),37,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1235,'Cash Register',DATETIME(),DATETIME(),37,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1239,'Contra Bank Account',DATETIME(),DATETIME(),37,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1240,'Company Credit Card',DATETIME(),DATETIME(),44,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (1250,'Credit Card Receipts',DATETIME(),DATETIME(),38,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2100,'Creditors Control Account',DATETIME(),DATETIME(),41,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2101,'Sundry Creditors',DATETIME(),DATETIME(),41,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2102,'Other Creditors',DATETIME(),DATETIME(),41,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2103,'Directors Loan Account',DATETIME(),DATETIME(),41,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2109,'Accruals',DATETIME(),DATETIME(),41,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2130,'Corporation Tax Payable',DATETIME(),DATETIME(),41,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2200,'Sales Tax Control Account',DATETIME(),DATETIME(),40,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2201,'Purchase Tax Control Account',DATETIME(),DATETIME(),40,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2202,'VAT Liability',DATETIME(),DATETIME(),40,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2204,'Manual Adjustments',DATETIME(),DATETIME(),40,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2210,'P.A.Y.E.',DATETIME(),DATETIME(),42,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2211,'National Insurance',DATETIME(),DATETIME(),42,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2214,'Student Loan Deductions',DATETIME(),DATETIME(),42,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2215,'CIS Deductions Suffered',DATETIME(),DATETIME(),42,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2220,'Net Wages',DATETIME(),DATETIME(),43,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2230,'Pension Fund',DATETIME(),DATETIME(),43,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2300,'Loans',DATETIME(),DATETIME(),47,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2301,'Directors Loan Account',DATETIME(),DATETIME(),47,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2310,'Hire Purchase',DATETIME(),DATETIME(),47,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2320,'Corporation Tax',DATETIME(),DATETIME(),47,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2330,'Mortgages',DATETIME(),DATETIME(),47,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (2340,'Dividend Liability',DATETIME(),DATETIME(),47,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (3000,'Ordinary Shares',DATETIME(),DATETIME(),48,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (3010,'Preference Shares',DATETIME(),DATETIME(),48,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (3100,'Reserves',DATETIME(),DATETIME(),49,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (3101,'Undistributed Reserves',DATETIME(),DATETIME(),49,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (3200,'Profit and Loss Account',DATETIME(),DATETIME(),49,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (3201,'Dividends Issued',DATETIME(),DATETIME(),49,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (3210,'Proposed Dividends',DATETIME(),DATETIME(),49,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4000,'Sales Type A',DATETIME(),DATETIME(),1,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4001,'Sales Type B',DATETIME(),DATETIME(),1,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4002,'Sales Type C',DATETIME(),DATETIME(),1,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4009,'Discounts Allowed',DATETIME(),DATETIME(),1,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4010,'Management Charges Receivable',DATETIME(),DATETIME(),1,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4049,'Flat Rate - Benefit/Cost',DATETIME(),DATETIME(),1,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4050,'Service Contract Income',DATETIME(),DATETIME(),2,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4055,'Courier Services Income',DATETIME(),DATETIME(),2,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4060,'Geopost Franchise Income',DATETIME(),DATETIME(),2,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4065,'Domain Fees Income',DATETIME(),DATETIME(),2,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4100,'Sales Type D',DATETIME(),DATETIME(),3,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4101,'Sales Type E',DATETIME(),DATETIME(),3,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4200,'Sales of Assets',DATETIME(),DATETIME(),4,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4400,'Credit Charges (Late Payments)',DATETIME(),DATETIME(),5,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4900,'Miscellaneous Income',DATETIME(),DATETIME(),6,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4901,'Royalties Received',DATETIME(),DATETIME(),6,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4902,'Commissions Received',DATETIME(),DATETIME(),6,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4903,'Insurance Claims',DATETIME(),DATETIME(),6,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4904,'Rent Income',DATETIME(),DATETIME(),6,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4905,'Distribution and Carriage',DATETIME(),DATETIME(),6,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (4910,'Bank Interest Received',DATETIME(),DATETIME(),6,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (5000,'Materials Purchased',DATETIME(),DATETIME(),7,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (5001,'Materials Imported',DATETIME(),DATETIME(),7,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (5002,'Miscellaneous Purchases',DATETIME(),DATETIME(),7,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (5003,'Packaging',DATETIME(),DATETIME(),7,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (5009,'Discounts Taken',DATETIME(),DATETIME(),7,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (5100,'Carriage',DATETIME(),DATETIME(),8,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (5101,'Import Duty',DATETIME(),DATETIME(),8,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (5102,'Transport Insurance',DATETIME(),DATETIME(),8,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (5200,'Opening Stock',DATETIME(),DATETIME(),9,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (5201,'Closing Stock',DATETIME(),DATETIME(),9,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (6000,'Productive Labour',DATETIME(),DATETIME(),10,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (6001,'Cost of Sales Labour',DATETIME(),DATETIME(),10,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (6002,'Sub-Contractors',DATETIME(),DATETIME(),10,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (6100,'Sales Commissions',DATETIME(),DATETIME(),11,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (6200,'Sales Promotions',DATETIME(),DATETIME(),12,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (6201,'Advertising',DATETIME(),DATETIME(),12,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (6202,'Gifts and Samples',DATETIME(),DATETIME(),12,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (6203,'P.R. (Literature & Brochures)',DATETIME(),DATETIME(),12,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (6900,'Miscellaneous Expenses',DATETIME(),DATETIME(),13,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (6905,'Franchise Costs',DATETIME(),DATETIME(),13,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (6910,'Delivery Vehicle Rental',DATETIME(),DATETIME(),13,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (6950,'Delivery Vehicle Fuel',DATETIME(),DATETIME(),13,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7000,'Gross Wages',DATETIME(),DATETIME(),14,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7001,'Directors Salaries',DATETIME(),DATETIME(),14,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7002,'Directors Remuneration',DATETIME(),DATETIME(),14,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7003,'Staff Salaries',DATETIME(),DATETIME(),14,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7004,'Wages - Regular',DATETIME(),DATETIME(),14,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7005,'Wages - Casual',DATETIME(),DATETIME(),14,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7006,'Employers N.I. (Non-Directors)',DATETIME(),DATETIME(),14,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7007,'Employers Pensions',DATETIME(),DATETIME(),14,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7008,'Recruitment Expenses',DATETIME(),DATETIME(),14,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7009,'Adjustments',DATETIME(),DATETIME(),14,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7010,'SSP Reclaimed',DATETIME(),DATETIME(),14,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7011,'SMP Reclaimed',DATETIME(),DATETIME(),14,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7012,'Employers N.I. (Directors)',DATETIME(),DATETIME(),14,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7013,'Employers N.I. Allowance',DATETIME(),DATETIME(),14,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7100,'Rent',DATETIME(),DATETIME(),15,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7102,'Water Rates',DATETIME(),DATETIME(),15,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7103,'General Rates',DATETIME(),DATETIME(),15,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7104,'Premises Insurance',DATETIME(),DATETIME(),15,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7105,'Self Storage Charges',DATETIME(),DATETIME(),15,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7200,'Electricity',DATETIME(),DATETIME(),16,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7201,'Gas',DATETIME(),DATETIME(),16,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7202,'Oil',DATETIME(),DATETIME(),16,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7203,'Other Heating Costs',DATETIME(),DATETIME(),16,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7300,'Vehicle Fuel',DATETIME(),DATETIME(),17,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7301,'Vehicle Repairs and Servicing',DATETIME(),DATETIME(),17,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7302,'Vehicle Licences',DATETIME(),DATETIME(),17,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7303,'Vehicle Insurance',DATETIME(),DATETIME(),17,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7304,'Miscellaneous Motor Expenses',DATETIME(),DATETIME(),17,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7305,'Congestion Charges',DATETIME(),DATETIME(),17,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7306,'Mileage Claims',DATETIME(),DATETIME(),17,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7307,'Courier Vehicle Insurance',DATETIME(),DATETIME(),17,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7350,'Scale Charges',DATETIME(),DATETIME(),17,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7400,'Travelling',DATETIME(),DATETIME(),18,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7401,'Car Hire',DATETIME(),DATETIME(),18,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7402,'Hotels',DATETIME(),DATETIME(),18,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7403,'U.K. Entertainment',DATETIME(),DATETIME(),18,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7404,'Overseas Entertainment',DATETIME(),DATETIME(),18,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7405,'Overseas Travelling',DATETIME(),DATETIME(),18,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7406,'Subsistence',DATETIME(),DATETIME(),18,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7500,'Printing',DATETIME(),DATETIME(),19,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7501,'Postage and Carriage',DATETIME(),DATETIME(),19,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7502,'Office Stationery',DATETIME(),DATETIME(),19,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7503,'Books etc.',DATETIME(),DATETIME(),19,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7550,'Telephone and Fax',DATETIME(),DATETIME(),20,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7551,'Internet Charges',DATETIME(),DATETIME(),20,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7552,'Computers & Software',DATETIME(),DATETIME(),20,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7553,'Mobile Charges',DATETIME(),DATETIME(),20,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7554,'Web Hosting Charges',DATETIME(),DATETIME(),20,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7555,'Domain Registration Fees',DATETIME(),DATETIME(),20,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7600,'Legal Fees',DATETIME(),DATETIME(),20,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7601,'Audit Fees',DATETIME(),DATETIME(),20,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7602,'Accountancy Fees',DATETIME(),DATETIME(),20,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7603,'Consultancy Fees',DATETIME(),DATETIME(),20,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7604,'Professional Fees',DATETIME(),DATETIME(),21,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7605,'Management Charges Payable',DATETIME(),DATETIME(),21,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7606,'Software Subscriptions',DATETIME(),DATETIME(),21,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7700,'Equipment Hire',DATETIME(),DATETIME(),22,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7701,'Office Machine Maintenance',DATETIME(),DATETIME(),22,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7702,'Equipment Leasing',DATETIME(),DATETIME(),22,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7703,'Leasing Costs',DATETIME(),DATETIME(),22,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7800,'Repairs and Renewals',DATETIME(),DATETIME(),23,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7801,'Cleaning',DATETIME(),DATETIME(),23,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7802,'Laundry',DATETIME(),DATETIME(),23,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7803,'Premises Expenses',DATETIME(),DATETIME(),23,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7900,'Bank Interest Paid',DATETIME(),DATETIME(),24,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7901,'Bank Charges',DATETIME(),DATETIME(),24,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7902,'Currency Charges',DATETIME(),DATETIME(),24,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7903,'Loan Interest Paid',DATETIME(),DATETIME(),24,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7904,'H.P. Interest',DATETIME(),DATETIME(),24,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7905,'Credit Charges',DATETIME(),DATETIME(),24,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7906,'Exchange Rate Variance',DATETIME(),DATETIME(),24,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7907,'Other Interest Charges',DATETIME(),DATETIME(),24,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (7908,'Factoring Charges',DATETIME(),DATETIME(),24,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (8000,'Depreciation',DATETIME(),DATETIME(),25,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (8001,'Plant/Machinery Depreciation',DATETIME(),DATETIME(),25,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (8002,'Furniture/Fitting Depreciation',DATETIME(),DATETIME(),25,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (8003,'Vehicle Depreciation',DATETIME(),DATETIME(),25,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (8004,'Office Equipment Depreciation',DATETIME(),DATETIME(),25,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (8100,'Bad Debt Write Off',DATETIME(),DATETIME(),26,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (8102,'Bad Debt Provision',DATETIME(),DATETIME(),26,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (8200,'Donations',DATETIME(),DATETIME(),27,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (8201,'Subscriptions',DATETIME(),DATETIME(),27,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (8202,'Clothing Costs',DATETIME(),DATETIME(),27,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (8203,'Training Costs',DATETIME(),DATETIME(),27,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (8204,'Insurance',DATETIME(),DATETIME(),27,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (8205,'Refreshments',DATETIME(),DATETIME(),27,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (8206,'Cash Register Discrepancies',DATETIME(),DATETIME(),27,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (8207,'GIT Insurance',DATETIME(),DATETIME(),27,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (8208,'P & E Liability Insurance',DATETIME(),DATETIME(),27,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (8250,'Sundry Expenses',DATETIME(),DATETIME(),27,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (9001,'Taxation',DATETIME(),DATETIME(),29,1);
INSERT INTO ledgers_nominalcode (nominal_code,nominal_name,created_at,updated_at,nominal_type_id,layout_id) VALUES (9998,'Suspense Account',DATETIME(),DATETIME(),28,1);