INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Product Sales',DATETIME(),DATETIME(),1);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Service Sales',DATETIME(),DATETIME(),1);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Export Sales',DATETIME(),DATETIME(),1);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Sales of Assets',DATETIME(),DATETIME(),1);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Credit Charges (Late Payments)',DATETIME(),DATETIME(),1);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Other Sales',DATETIME(),DATETIME(),1);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Purchases',DATETIME(),DATETIME(),2);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Purchase Charges',DATETIME(),DATETIME(),2);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Stock',DATETIME(),DATETIME(),2);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Labour',DATETIME(),DATETIME(),3);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Commissions',DATETIME(),DATETIME(),3);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Sales Promotion',DATETIME(),DATETIME(),3);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Miscellaneous Expenses',DATETIME(),DATETIME(),3);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Gross Wages',DATETIME(),DATETIME(),4);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Rent and Rates',DATETIME(),DATETIME(),4);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Heat, Light and Power',DATETIME(),DATETIME(),4);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Motor Expenses',DATETIME(),DATETIME(),4);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Travelling and Entertainment',DATETIME(),DATETIME(),4);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Printing and Stationery',DATETIME(),DATETIME(),4);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Telephone and Computer charges',DATETIME(),DATETIME(),4);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Professional Fees',DATETIME(),DATETIME(),4);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Equipment Hire and Rental',DATETIME(),DATETIME(),4);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Maintenance',DATETIME(),DATETIME(),4);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Bank Charges and Interest',DATETIME(),DATETIME(),4);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Depreciation',DATETIME(),DATETIME(),4);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Bad Debts',DATETIME(),DATETIME(),4);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('General Expenses',DATETIME(),DATETIME(),4);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Suspense & Mispostings',DATETIME(),DATETIME(),4);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Taxation',DATETIME(),DATETIME(),5);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Property',DATETIME(),DATETIME(),6);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Plant and Machinery',DATETIME(),DATETIME(),6);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Office Equipment',DATETIME(),DATETIME(),6);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Furniture and Fixtures',DATETIME(),DATETIME(),6);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Motor Vehicles',DATETIME(),DATETIME(),6);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Stock',DATETIME(),DATETIME(),7);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Debtors',DATETIME(),DATETIME(),7);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Deposits and Cash',DATETIME(),DATETIME(),7);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Credit Card (Debtors)',DATETIME(),DATETIME(),7);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Bank Account',DATETIME(),DATETIME(),7);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('VAT Liability',DATETIME(),DATETIME(),7);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Creditors : Short Term',DATETIME(),DATETIME(),8);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Payroll Taxation',DATETIME(),DATETIME(),8);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Wages',DATETIME(),DATETIME(),8);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Credit Card (Creditors)',DATETIME(),DATETIME(),8);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Bank Account',DATETIME(),DATETIME(),8);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('VAT Liability',DATETIME(),DATETIME(),8);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Creditors : Long Term',DATETIME(),DATETIME(),9);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Share Capital',DATETIME(),DATETIME(),10);
INSERT INTO ledgers_nominaltype (type_name,created_at,updated_at,coa_category_id) VALUES ('Reserves',DATETIME(),DATETIME(),10);