import { FormFieldType } from '../../types/FormField';

export const CoaLayoutDialogFields: FormFieldType[] = [
    // Row 1: ID (25%) + Layout (25%) + Layout Name (50%)
    {
        autoFocus: true,
        disabled: true,
        fullWidth: true,
        id: 'id',
        label: 'ID',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '25%', maxWidth: '25%' },
        type: 'number',
        variant: 'outlined',
    },
    {
        autoFocus: true,
        disabled: false,
        fullWidth: true,
        id: 'layout',
        label: 'Layout',
        margin: 'dense',
        required: true,
        sx: { flexBasis: '25%', maxWidth: '25%' },
        type: 'select',
        variant: 'outlined',
        options: [], // TODO: Populate with layout options
    },
    {
        autoFocus: false,
        disabled: true,
        fullWidth: true,
        id: 'layout_name',
        label: 'Layout Name',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'text',
        variant: 'outlined',
    },
    // Row 2: Nominal Type (select) + Nominal Type Name (display)
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'nominal_type',
        label: 'Nominal Type',
        margin: 'dense',
        required: true,
        sx: { flexBasis: '25%', maxWidth: '25%' },
        type: 'select',
        variant: 'outlined',
        options: [], // TODO: Populate with nominal type options
    },
    {
        autoFocus: false,
        disabled: true,
        fullWidth: true,
        id: 'nominal_type_name',
        label: 'Nominal Type Name',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '75%', maxWidth: '75%' },
        type: 'text',
        variant: 'outlined',
    },
    // Row 3: Nominal Code Min/Max (50/50)
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'nominal_code_min',
        label: 'Nominal Code Min',
        margin: 'dense',
        required: true,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'number',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'nominal_code_max',
        label: 'Nominal Code Max',
        margin: 'dense',
        required: true,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'number',
        variant: 'outlined',
    },
    // Row 4: Created/Updated (system fields)
    {
        autoFocus: false,
        disabled: true,
        fullWidth: true,
        id: 'created_at',
        label: 'Created',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'text',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: true,
        fullWidth: true,
        id: 'updated_at',
        label: 'Updated',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'text',
        variant: 'outlined',
    },
];
