import { TextFieldProps } from '@mui/material';

export const CoaLayoutDialogFields: TextFieldProps[] = [
    {
        autoFocus: true,
        margin: 'dense',
        id: 'id',
        label: 'ID',
        type: 'number',
        fullWidth: true,
        variant: 'outlined',
        disabled: true,
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'layout',
        label: 'Layout',
        type: 'number',
        fullWidth: false,
        variant: 'outlined',
        sx: { width: '25%' },
        required: true,
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'layout_name',
        label: 'Layout Name',
        type: 'text',
        fullWidth: false,
        variant: 'outlined',
        sx: { width: '75%' },
        disabled: true,
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'nominal_type',
        label: 'Nominal Type',
        type: 'number',
        fullWidth: false,
        variant: 'outlined',
        sx: { width: '25%' },
        required: true,
    },
    {
        autoFocus: true,
        margin: 'dense',
        id: 'nominal_type_name',
        label: 'Nominal Type',
        type: 'text',
        fullWidth: false,
        variant: 'outlined',
        sx: { width: '75%' },
        disabled: true,
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'nominal_code_min',
        label: 'N/C Min',
        type: 'number',
        fullWidth: false,
        variant: 'outlined',
        sx: { width: '50%' },
        required: true,
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'nominal_code_max',
        label: 'N/C Max',
        type: 'number',
        fullWidth: false,
        variant: 'outlined',
        sx: { width: '50%' },
        required: true,
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'created_at',
        label: 'Created',
        type: 'text',
        fullWidth: true,
        variant: 'outlined',
        sx: { width: '50%' },
        disabled: true,
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'updated_at',
        label: 'Updated',
        type: 'text',
        fullWidth: false,
        variant: 'outlined',
        sx: { width: '50%' },
        disabled: true,
    },
];
