# Generated by Django 4.1.6 on 2023-02-13 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
