# Generated by Django 4.1.6 on 2023-02-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_user_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="job_title",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
