# Generated by Django 4.1.6 on 2023-02-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_user_job_title_user_nickname_user_website"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="following",
            new_name="follow",
        ),
    ]
