# Generated by Django 4.1.6 on 2023-03-02 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_rename_following_user_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                default=0, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
