import { FormField } from '../../types/FormField';

export const NominalCodeDialogFields: FormField[] = [
    // Row 1: ID (25%) + Nominal Code (75%)
    {
        autoFocus: true,
        disabled: true,
        fullWidth: true,
        id: 'id',
        label: 'ID',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '25%', maxWidth: '25%' },
        type: 'number',
        variant: 'outlined',
    },
    {
        autoFocus: true,
        disabled: false,
        fullWidth: true,
        id: 'nominal_code',
        label: 'Nominal Code',
        margin: 'dense',
        required: true,
        sx: { flexBasis: '75%', maxWidth: '75%' },
        type: 'text',
        variant: 'outlined',
    },
    // Row 2: Nominal Name (full width)
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'nominal_name',
        label: 'Nominal Name',
        margin: 'dense',
        required: true,
        sx: {},
        type: 'text',
        variant: 'outlined',
    },
    // Row 3: Layout (select, 50%) + Layout Name (display, 50%)
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'layout',
        label: 'Layout',
        margin: 'dense',
        required: true,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'select',
        variant: 'outlined',
        options: [], // TODO: Populate with layout options
    },
    {
        autoFocus: false,
        disabled: true,
        fullWidth: true,
        id: 'layout_name',
        label: 'Layout Name',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'text',
        variant: 'outlined',
    },
    // Row 4: Nominal Type (select, 50%) + Type Name (display, 50%)
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'nominal_type',
        label: 'Nominal Type',
        margin: 'dense',
        required: true,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'select',
        variant: 'outlined',
        options: [], // TODO: Populate with nominal type options
    },
    {
        autoFocus: false,
        disabled: true,
        fullWidth: true,
        id: 'type_name',
        label: 'Nominal Type Name',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'text',
        variant: 'outlined',
    },
    // Row 5: Created/Updated (system fields)
    {
        autoFocus: false,
        disabled: true,
        fullWidth: true,
        id: 'created_at',
        label: 'Created',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'text',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: true,
        fullWidth: true,
        id: 'updated_at',
        label: 'Updated',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'text',
        variant: 'outlined',
    },
];
