import { FormField } from '../../types/FormField';

const SupplierDialogFields: FormField[] = [
    {
        autoFocus: true,
        disabled: true,
        fullWidth: true,
        id: 'id',
        label: 'ID',
        margin: 'dense',
        required: false,
        sx: {},
        type: 'number',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'account_reference',
        label: 'Account Reference',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '25%', maxWidth: '25%' },
        type: 'text',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'account_name',
        label: 'Account Name',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '75%', maxWidth: '75%' },
        type: 'text',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'account_status',
        label: 'Account Status',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '33.33%', maxWidth: '33.33%' },
        type: 'text',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'credit_limit',
        label: 'Credit Limit',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '33.33%', maxWidth: '33.33%' },
        type: 'number',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'balance',
        label: 'Balance',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '33.33%', maxWidth: '33.33%' },
        type: 'number',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'contact_name',
        label: 'Contact Name',
        margin: 'dense',
        required: false,
        sx: {},
        type: 'text',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'telephone_number',
        label: 'Telephone Number',
        margin: 'dense',
        required: false,
        sx: {},
        type: 'text',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: true,
        fullWidth: true,
        id: 'created_at',
        label: 'Created At',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'text',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: true,
        fullWidth: true,
        id: 'updated_at',
        label: 'Updated At',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'text',
        variant: 'outlined',
    },
];

export default SupplierDialogFields;
