# Generated by Django 4.2 on 2023-10-08 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Banking",
            new_name="BankAccount",
        ),
        migrations.AlterModelOptions(
            name="bankaccount",
            options={"verbose_name_plural": "Bank Accounts"},
        ),
    ]
