# Generated by Django 4.0.5 on 2023-01-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comment_text',
        ),
        migrations.AddField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(related_name='listings', to='auctions.comment'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title'], name='category_title_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['title'], name='listing_title_idx'),
        ),
    ]
