# Generated by Django 4.0.5 on 2023-01-07 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_listing_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='text',
        ),
    ]
