# Generated by Django 4.0.5 on 2023-01-08 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_remove_watchlist_listing_watchlist_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ManyToManyField(related_name='watchlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
