# Generated by Django 4.0.5 on 2023-01-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_remove_watchlist_user_watchlist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
