# Generated by Django 4.0.5 on 2023-01-08 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_delete_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listings', models.ManyToManyField(related_name='watchlists', to='auctions.listing')),
                ('user', models.ManyToManyField(related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
