# Generated by Django 4.0.5 on 2023-01-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_watchlist_listing_watchlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
    ]
