# Generated by Django 4.2 on 2023-10-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ledgers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nominalcodes",
            name="coa_category",
        ),
        migrations.AddField(
            model_name="nominaltypes",
            name="coa_category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coa_category",
                to="ledgers.coacategories",
            ),
            preserve_default=False,
        ),
    ]
