# Generated by Django 4.2 on 2023-10-08 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ledgers", "0002_remove_nominalcodes_coa_category_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CoaCategories",
            new_name="CoaCategory",
        ),
        migrations.RenameModel(
            old_name="CoaLayouts",
            new_name="CoaLayout",
        ),
        migrations.RenameModel(
            old_name="NominalCodes",
            new_name="NominalCode",
        ),
        migrations.RenameModel(
            old_name="NominalTypes",
            new_name="NominalType",
        ),
        migrations.AlterModelOptions(
            name="coacategory",
            options={"verbose_name_plural": "Coa Categories"},
        ),
        migrations.AlterModelOptions(
            name="coalayout",
            options={"verbose_name_plural": "Coa Layouts"},
        ),
        migrations.AlterModelOptions(
            name="nominalcode",
            options={"verbose_name_plural": "Nominal Codes"},
        ),
        migrations.AlterModelOptions(
            name="nominaltype",
            options={"verbose_name_plural": "Nominal Types"},
        ),
    ]
