# Generated by Django 4.2 on 2023-10-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ledgers", "0003_rename_coacategories_coacategory_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CoaLayout",
            new_name="Layout",
        ),
        migrations.AlterModelOptions(
            name="layout",
            options={"verbose_name_plural": "Layouts"},
        ),
        migrations.RemoveField(
            model_name="nominalcode",
            name="coa_layout",
        ),
        migrations.AddField(
            model_name="nominalcode",
            name="layout",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="layout",
                to="ledgers.layout",
            ),
            preserve_default=False,
        ),
    ]
