# Generated by Django 4.2 on 2023-10-09 23:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ledgers", "0005_coalayout"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coalayout",
            old_name="nominal_codes_max",
            new_name="nominal_code_max",
        ),
        migrations.RenameField(
            model_name="coalayout",
            old_name="nominal_codes_min",
            new_name="nominal_code_min",
        ),
    ]
