# Generated by Django 5.2.4 on 2025-07-31 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ledgers",
            "0006_rename_nominal_codes_max_coalayout_nominal_code_max_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="coalayout",
            name="layout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coa_layouts",
                to="ledgers.layout",
            ),
        ),
        migrations.AlterField(
            model_name="coalayout",
            name="nominal_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coa_layouts",
                to="ledgers.nominaltype",
            ),
        ),
    ]
