# Generated by Django 4.2 on 2023-10-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_reference", models.CharField(max_length=255)),
                ("account_name", models.CharField(max_length=255)),
                ("account_status", models.CharField(max_length=255)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="balance"
                    ),
                ),
                ("contact_name", models.CharField(max_length=255)),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="credit limit"
                    ),
                ),
                ("telephone_number", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
