import { FormFieldType } from '../../types/FormField';

const BankingAccountListDialogFields: FormFieldType[] = [
    // Account Details
    {
        autoFocus: true,
        disabled: true,
        fullWidth: true,
        id: 'id',
        label: 'ID',
        margin: 'dense',
        required: false,
        sx: {},
        type: 'number',
        variant: 'outlined',
    },
    {
        autoFocus: true,
        disabled: false,
        fullWidth: true,
        id: 'account_name',
        label: 'Account Name',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '75%', maxWidth: '75%' },
        type: 'text',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'account_number',
        label: 'Account Number',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '25%', maxWidth: '25%' },
        type: 'number',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'account_sort_code',
        label: 'Sort Code',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'text',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'account_type',
        label: 'Account Type',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'text',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'currency',
        label: 'Currency',
        margin: 'dense',
        required: false,
        sx: {},
        type: 'text',
        variant: 'outlined',
    },
    // Status & Limits
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'account_status',
        label: 'Account Status',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '33.33%', maxWidth: '33.33%' },
        type: 'text',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'credit_limit',
        label: 'Credit Limit',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '33.33%', maxWidth: '33.33%' },
        type: 'number',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'balance',
        label: 'Balance',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '33.33%', maxWidth: '33.33%' },
        type: 'number',
        variant: 'outlined',
    },
    // Opening Balance
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'opening_balance',
        label: 'Opening Balance',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'number',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: false,
        fullWidth: true,
        id: 'opening_balance_date',
        label: 'Opening Balance Date',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'text',
        variant: 'outlined',
    },
    // Timestamps
    {
        autoFocus: false,
        disabled: true,
        fullWidth: true,
        id: 'created_at',
        label: 'Created',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'text',
        variant: 'outlined',
    },
    {
        autoFocus: false,
        disabled: true,
        fullWidth: true,
        id: 'updated_at',
        label: 'Updated',
        margin: 'dense',
        required: false,
        sx: { flexBasis: '50%', maxWidth: '50%' },
        type: 'text',
        variant: 'outlined',
    },
];
export default BankingAccountListDialogFields;
